[RoutingConfig]
app_id = "MyApp"
hostname   = "lolcatho.st"
path_begin = "/api" # optional
certificate = "../lib/assets/certificate.pem" # optional
key = "../lib/assets/key.pem" # optional
certificate_chain = "../lib/assets/certificate_chain.pem" # optional
frontends = ["HTTP", "HTTPS"] # list of proxy tags
backends  = [ "127.0.0.1:1026" ] # list of IP/port